### ISSUE TITLE
KawaiiEmotes broken with July 20 update

### ISSUE THREAD

**Issue by Adowrath** [noodlebox/betterdiscord-plugins#23] opened 2017-07-25 22:11 UTC
KawaiiEmotes has stopped working with this new update. I have located one of the issues - they changed classes of the `.channel-textarea` divs (for me it always includes a class of `.channelTextAreaEnabled-c05Zpy`). I fixed that for me locally, but still two issues remain:

* The completion window is largely unstyled and placed below the textarea, not above it.
* Completion doesn't correctly update the value for some reason. How to replicate: Type Kurisu, choose one of the completions, immediately hit enter. _Kurisu_ gets printed, not the Emote. I tried my best but couldn't locate the source of this issue.

It'd be awesome if you could update the plugin so it works again, thank you.

**Comment by noodlebox** [comment] 2017-07-25 22:13
Should already be fixed (duplicate of #19). Just try updating to 0.4.4.

**Closed as completed** 2017-07-25 22:16 UTC
Labels: duplicate

**Comment by Adowrath** [comment] 2017-07-26 19:33
Eh, darnit, didn't think about checking the closed issues, and forgot to check if there was a new release in the time between my friend telling me it's broken to me actually getting to find the errors, sorry. And thanks for the fix and fast reply!
