### ISSUE TITLE
Autoplay Gifs broke because of React 16

### ISSUE THREAD

**Issue by Abyss1992** [noodlebox/betterdiscord-plugins#28] opened 2017-10-06 10:01 UTC

**Comment by noodlebox** [comment] 2017-10-06 10:21
Thanks for reporting, but I already have an issue open for this. (duplicate of #27)

**Closed as completed by noodlebox** 2017-10-06 10:21 UTC
Labels: duplicate

**Comment by Abyss1992** [comment] 2017-10-06 10:42
Cool any ETA or is it just when ever you get to it?

**Comment by noodlebox** [comment] 2017-10-06 11:44
I'll probably get to this later today, it just depends on how much digging around I have to do in the new code.
