### ISSUE TITLE
KawaiiEmotes: Completion Box Broke

### ISSUE THREAD

**Issue by ghost** [noodlebox/betterdiscord-plugins#21] opened 2017-07-22 05:37 UTC
Seems to have just broke in the latest Discord update [July 20, 2017]. They gave the textarea a 'facelift' and seemed to broke something, tried tweaking with it but failed.

**Comment by noodlebox** [comment] 2017-07-22 13:37
Thanks for reporting, though this is a duplicate of #19. The changes from Canary have made their way into the stable version.

**Closed as completed by noodlebox** 2017-07-22 13:37 UTC
Labels: duplicate
