### ISSUE TITLE
owner tags not loading 

### ISSUE THREAD

**Issue by kmddd59** [noodlebox/betterdiscord-plugins#29] opened 2017-10-07 16:58 UTC
not sure if this helps

`Last login: Sat Oct  7 07:32:23 on ttys000
Tims-MacBook-Air:~ maefarris$ /Applications/Discord\ PTB.app/Contents/MacOS/Discord\ PTB 
DiscordPtb 0.0.31
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /Users/maefarris/Library/Application Support/discordptb/0.0.31/modules
2017-10-07 09:56:19.193 Discord PTB[47098:7756901] *** WARNING: Textured window <AtomNSWindow: 0x7fb7dfcbce20> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/ptb/versions.json
[Modules] No module updates available.
[BetterDiscord INF] Hooking dom-ready
[BetterDiscord INF] Checking data/cache
[BetterDiscord INF] Using repository: Jiiks and branch: master
[BetterDiscord INF] Getting latest hash
[BetterDiscord INF] Downloading Resource: api.github.com/repos/Jiiks/BetterDiscordApp/commits/master
[Modules] Checking for host updates.
[BetterDiscord INF] Hooked dom-ready
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/ptb/versions.json
[Modules] No module updates available.
[BetterDiscord INF] Hash: 9ab77a8217ef2d3ef648f4cef9f9eeaa9c571a86
[BetterDiscord INF] Getting updater
[BetterDiscord INF] Downloading Resource: raw.githubusercontent.com/Jiiks/BetterDiscordApp/9ab77a8217ef2d3ef648f4cef9f9eeaa9c571a86/data/updater.json
[BetterDiscord INF] Latest Version: 0.2.7
[BetterDiscord INF] Using CDN: cdn.rawgit.com
[BetterDiscord INF] Updating ext data
[BetterDiscord INF] Loading
[BetterDiscord INF] Hooking ipc async
[BetterDiscord INF] Hooked ipc async
[BetterDiscord INF] Loading Resource (jQuery)
[BetterDiscord INF] Invalid plugin detected: .DS_Store
[BetterDiscord INF] Loading plugin: p_1lib_discord_internals
[BetterDiscord INF] Loading plugin: autoGif
[BetterDiscord INF] Loading plugin: BetterFormatting
[BetterDiscord INF] Loading plugin: BlurNSFW
[BetterDiscord INF] Invalid plugin detected: CreationDate.config.json
[BetterDiscord INF] Invalid plugin detected: CustomNotifications.config.json
[BetterDiscord INF] Loading plugin: ownerTag
[BetterDiscord INF] Invalid plugin detected: Quicksave.config.json
[BetterDiscord INF] Loading plugin: Quicksave
[BetterDiscord INF] Loading plugin: betaPlugin
[BetterDiscord INF] Loading plugin: charCounter
[BetterDiscord INF] Loading plugin: dblClickEdit
[BetterDiscord INF] Loading plugin: directDownload
[BetterDiscord INF] Loading plugin: evenBetterRepo
[BetterDiscord INF] Loading plugin: p_full_offline_list
[BetterDiscord INF] Invalid plugin detected: hideServers.config.json
[BetterDiscord INF] Loading plugin: hideServers
[BetterDiscord INF] Invalid plugin detected: link-stub.md
[BetterDiscord INF] Loading plugin: linkProfilePicture
[BetterDiscord INF] Invalid plugin detected: quoter.config.json
[BetterDiscord INF] Loading plugin: p_quoter
[BetterDiscord INF] Invalid plugin detected: restartNoMore.config.json
[BetterDiscord INF] Loading plugin: restartNoMore
[BetterDiscord INF] Loading plugin: transparency_patcher
[BetterDiscord INF] Loading plugin: typingSoundPlugin
[BetterDiscord INF] Loading plugin: unshortenLinks
[BetterDiscord INF] Invalid theme detected .DS_Store
[BetterDiscord INF] Loading theme: Chat_Text_Bubbles
[BetterDiscord INF] Loading theme: Chat_Text_Bubbles_Minified
[BetterDiscord INF] Loading theme: IOS_switches
[BetterDiscord INF] Loading theme: Mutual_Servers_Server_Count
[BetterDiscord INF] Loading theme: Transparency
[BetterDiscord INF] Loading theme: Full_Dark
[BetterDiscord INF] Invalid theme detected fulldark.theme.css.txt
[BetterDiscord INF] Loading theme: Modal-anim-8
[BetterDiscord INF] Loading Resource (jQueryCookie)
[BetterDiscord INF] Loading Resource (Main CSS)
[BetterDiscord INF] Loading Resource (Main JS)
[BetterDiscord INF] Loading Resource (Twitch Global Emotedata)
[BetterDiscord INF] Reading Twitch Global Emotedata from file
[BetterDiscord INF] Validating Twitch Global Emotedata
[BetterDiscord WRN] Twitch Global Emotedata is invalid
[BetterDiscord INF] Deleting cached file Twitch Global Emotedata
[BetterDiscord INF] Loading Resource (Twitch Global Emotedata)
[BetterDiscord INF] Downloading Resource: twitchemotes.com/api_cache/v2/global.json
[BetterDiscord INF] Parsing: Twitch Global Emotedata
[BetterDiscord INF] Saving resource to file Twitch Global Emotedata
[BetterDiscord INF] Loading Resource (Twitch Subscriber Emotedata)
[BetterDiscord INF] Reading Twitch Subscriber Emotedata from file
[BetterDiscord INF] Validating Twitch Subscriber Emotedata
[BetterDiscord INF] Twitch Subscriber Emotedata is valid
[BetterDiscord INF] Loading Resource (FrankerFaceZ Emotedata)
[BetterDiscord INF] Reading FrankerFaceZ Emotedata from file
[BetterDiscord INF] Validating FrankerFaceZ Emotedata
[BetterDiscord INF] FrankerFaceZ Emotedata is valid
[BetterDiscord INF] Loading Resource (BTTV Emotedata)
[BetterDiscord INF] Reading BTTV Emotedata from file
[BetterDiscord INF] Validating BTTV Emotedata
[BetterDiscord INF] BTTV Emotedata is valid
[BetterDiscord INF] Loading Resource (BTTV Emotedata)
[BetterDiscord INF] Reading BTTV Emotedata from file
[BetterDiscord INF] Validating BTTV Emotedata
[BetterDiscord INF] BTTV Emotedata is valid
[BetterDiscord INF] Starting Up

`

**Comment by noodlebox** [comment] 2017-10-07 19:39
Duplicate of #27

**Closed as completed** 2017-10-07 19:40 UTC
Labels: duplicate
